name: docq_app
description: A Flutter project with Clean Architecture using Riverpod, Dio, and Firebase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  google_fonts: ^6.1.0
  qr_flutter: ^4.1.0

  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Network
  dio: ^5.4.0
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  
  # Navigation
  go_router: ^12.1.3
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Utils
  equatable: ^2.0.5
  dartz: ^0.10.1
  table_calendar: ^3.2.0
  lucide_icons: ^0.257.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code generation
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
